apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  annotations:
    infinispan.org/monitoring: 'true'
  name: example-infinispan
  namespace: devopsdays
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app: infinispan-pod
                clusterName: example-infinispan
                infinispan_cr: example-infinispan
            topologyKey: kubernetes.io/hostname
          weight: 100
  configListener:
    enabled: true
    logging:
      level: info
  container:
    memory: 1Gi
  replicas: 2
  security:
    endpointAuthentication: true
    endpointEncryption:
      clientCert: None
      type: None
    endpointSecretName: example-infinispan-generated-secret
  service:
    replicationFactor: 2
    type: Cache
  upgrades:
    type: Shutdown
  version: 14.0.6

